from html import escape
import os
import time
from datetime import datetime, timezone
import logging

import httpx

import config

logger = logging.getLogger(__name__)


def _esc(value) -> str:
    """HTML-escape a string value."""
    return escape(str(value)) if value else ""


def _build_html(papers: list[dict], posts: list[dict], now: datetime) -> str:
    """Build the HTML email body for the research digest."""
    week_date = now.strftime("%B %-d, %Y")
    timestamp = now.strftime("%Y-%m-%d %H:%M UTC")

    # --- Papers section ---
    if papers:
        paper_items = ""
        for p in papers:
            abstract = p.get("abstract", "") or ""
            if len(abstract) > 300:
                abstract = abstract[:300] + "..."
            url = _esc(p.get("url", "#"))
            authors = p.get("authors", [])
            authors_str = _esc(", ".join(authors) if isinstance(authors, list) else str(authors))
            paper_items += (
                '<div style="margin-bottom: 20px; padding: 15px; background: #f8fafc; '
                'border-left: 3px solid #2563eb; border-radius: 4px;">\n'
                f'  <h3 style="margin: 0 0 5px;"><a href="{url}" style="color: #2563eb;">'
                f'{_esc(p.get("title", "Untitled"))}</a></h3>\n'
                f'  <p style="color: #64748b; margin: 5px 0; font-size: 14px;">'
                f'{authors_str} | {_esc(p.get("journal", ""))} | {_esc(p.get("publication_date", ""))}</p>\n'
                f'  <p style="font-size: 14px; margin: 5px 0;">{_esc(abstract)}</p>\n'
                f'  <p style="color: #059669; font-style: italic; margin: 5px 0; font-size: 14px;">'
                f'<strong>Why it\'s relevant:</strong> {_esc(p.get("note", ""))}</p>\n'
                '</div>\n'
            )
        papers_section = (
            f'<h2>\U0001f4c4 Relevant Academic Papers ({len(papers)} found)</h2>\n'
            + paper_items
        )
    else:
        papers_section = (
            '<h2>\U0001f4c4 Relevant Academic Papers (0 found)</h2>\n'
            '<p>No relevant papers this week.</p>\n'
        )

    # --- Posts section ---
    if posts:
        post_items = ""
        for p in posts:
            handle = _esc(p.get("author_handle", p.get("handle", "")))
            name = _esc(p.get("author_name", p.get("name", "")))
            url = _esc(p.get("url", "#"))
            post_items += (
                '<div style="margin-bottom: 15px; padding: 15px; background: #f8fafc; '
                'border-left: 3px solid #8b5cf6; border-radius: 4px;">\n'
                f'  <p style="margin: 0 0 5px;"><strong><a href="{url}" style="color: #8b5cf6;">'
                f'{name}</a></strong> '
                f'<span style="color: #94a3b8;">@{handle}</span></p>\n'
                f'  <p style="margin: 5px 0;">{_esc(p.get("text", ""))}</p>\n'
                f'  <p style="color: #059669; font-style: italic; margin: 5px 0; font-size: 14px;">'
                f'<strong>Why it\'s relevant:</strong> {_esc(p.get("note", ""))}</p>\n'
                '</div>\n'
            )
        posts_section = (
            f'<h2>\U0001f4ac Relevant Bluesky Posts ({len(posts)} found)</h2>\n'
            + post_items
        )
    else:
        posts_section = (
            '<h2>\U0001f4ac Relevant Bluesky Posts (0 found)</h2>\n'
            '<p>No relevant posts this week.</p>\n'
        )

    html = (
        '<html>\n'
        '<body style="font-family: -apple-system, BlinkMacSystemFont, \'Segoe UI\', '
        'Roboto, sans-serif; max-width: 700px; margin: 0 auto; padding: 20px; color: #333;">\n'
        f'  <h1 style="border-bottom: 2px solid #2563eb; padding-bottom: 10px;">'
        f'Research Digest \u2014 Week of {week_date}</h1>\n'
        f'  \n'
        f'  {papers_section}\n'
        f'  {posts_section}\n'
        f'  <hr style="border: none; border-top: 1px solid #e2e8f0; margin: 30px 0;">\n'
        f'  <p style="color: #94a3b8; font-size: 12px;">Generated by journal-retrieval agent. '
        f'Run at {timestamp}.</p>\n'
        '</body>\n'
        '</html>'
    )
    return html


def send_digest(papers: list[dict], posts: list[dict]) -> bool:
    """Send the research digest as an HTML email via Resend API.

    Returns True on success, False on failure.
    """
    now = datetime.now(timezone.utc)
    week_date = now.strftime("%B %-d, %Y")
    subject = f"Research Digest \u2014 Week of {week_date}"

    html_body = _build_html(papers, posts, now)

    for attempt in range(3):
        try:
            response = httpx.post(
                "https://api.resend.com/emails",
                headers={"Authorization": f"Bearer {config.RESEND_API_KEY}"},
                json={
                    "from": config.SENDER_EMAIL,
                    "to": [config.RECIPIENT_EMAIL],
                    "subject": subject,
                    "html": html_body,
                },
                timeout=30.0,
            )
            if response.status_code == 200:
                logger.info("Digest email sent to %s.", config.RECIPIENT_EMAIL)
                return True
            logger.warning(
                "Resend API returned %d: %s (attempt %d/3)",
                response.status_code, response.text, attempt + 1,
            )
        except (httpx.HTTPError, OSError) as exc:
            logger.warning("Resend API error (attempt %d/3): %s", attempt + 1, exc)

        if attempt < 2:
            delay = 2 * (2 ** attempt)
            time.sleep(delay)

    logger.error("Failed to send digest email after 3 attempts.")
    return False


def save_report(papers: list[dict], posts: list[dict], output_dir: str = "reports") -> str:
    """Save the digest as a markdown file in the output directory.

    Returns the path to the saved file.
    """
    now = datetime.now(timezone.utc)
    timestamp = now.strftime("%Y-%m-%d %H:%M UTC")
    date_str = now.strftime("%Y-%m-%d")

    os.makedirs(output_dir, exist_ok=True)
    filepath = os.path.join(output_dir, f"{date_str}.md")

    lines: list[str] = []
    lines.append(f"# Research Digest \u2014 {date_str}\n")

    # --- Papers ---
    lines.append(f"\n## Academic Papers ({len(papers)} relevant)\n")
    if papers:
        for p in papers:
            lines.append(f"\n### {p.get('title', 'Untitled')}")
            authors = p.get('authors', [])
            authors_str = ", ".join(authors) if isinstance(authors, list) else str(authors)
            lines.append(f"**Authors**: {authors_str}  ")
            lines.append(f"**Journal**: {p.get('journal', 'N/A')} | **Date**: {p.get('publication_date', 'N/A')}  ")
            lines.append(f"**URL**: {p.get('url', 'N/A')}\n")
            lines.append(f"{p.get('abstract', 'No abstract available.')}\n")
            lines.append(f"> **Why it's relevant:** {p.get('note', 'N/A')}\n")
            lines.append("---\n")
    else:
        lines.append("\nNo relevant papers this week.\n")

    # --- Posts ---
    lines.append(f"\n## Bluesky Posts ({len(posts)} relevant)\n")
    if posts:
        for p in posts:
            handle = p.get("author_handle", p.get("handle", ""))
            name = p.get("author_name", p.get("name", ""))
            lines.append(f"\n### {name} (@{handle})")
            lines.append(f"{p.get('text', '')}\n")
            lines.append(f"**URL**: {p.get('url', 'N/A')}\n")
            lines.append(f"> **Why it's relevant:** {p.get('note', 'N/A')}\n")
            lines.append("---\n")
    else:
        lines.append("\nNo relevant posts this week.\n")

    lines.append(f"\n*Generated by journal-retrieval agent at {timestamp}.*\n")

    with open(filepath, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    logger.info("Report saved to %s.", filepath)
    return filepath
